{% set version = "5.4.2" %}

package:
  name: android-liblzma
  version: '{{ version }}'

source:
  url: https://downloads.sourceforge.net/project/lzmautils/xz-{{version}}.tar.xz
  sha256: 3ee13d0f40148625306b90f9622f8c9660b8082884051b0cfe46f18492f88955

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-ndk

about:
  home: http://github.com/codelv/enaml-native
  summary: XZ Utils is free general-purpose data compression software with a high compression ratio. XZ Utils were written for POSIX-like systems, but also work on some not-so-POSIX systems. XZ Utils are the successor to LZMA Utils.
  license: public domain
