{% set name = "enaml" %}
{% set version = "0.10.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9a3a16f859372f50b1cb2868ea033f8e3724ce0cc8dbdd0dae0cb5f407b44a27" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - enaml=={{ version }}
    - android-atom>=0.4.3 py{{CONDA_PY}}*
  run:
    - python
    - android-atom>=0.4.3# py{{CONDA_PY}}*
    - pip-ply==3.11

build:
  number: 0
  binary_relocation: False
  noarch: generic

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
