context:
  name: atom
  version: 0.8.0
  hash_type: sha256
  hash_value: 4055fbdeeb692d3d52c6e3c628d7513fc71f147920cac7d0da05b6dbb5ec8c8d

package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  git_url: https://github.com/nucleic/atom.git
  git_rev: main
  #fn: '{{ name }}-{{ version }}.tar.gz'
  #url: 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
  #'{{ hash_type }}': '{{ hash_value }}'


requirements:
  build:
    - python
    - cppy
    - pip-cppy
    - android-ndk
    - android-libcxx
    - android-python * py310*
  run:
    - python
    - android-libcxx
    - android-python * py310*

build:
  binary_relocation: false
  noarch: generic

about:
  home: https://github.com/nucleic/atom
  summary: Memory efficient Python objects
  license: BSD

