diff --git a/lib/Makefile.bak b/lib/Makefile
index 533b4b1..967994a 100644
--- a/lib/Makefile.bak
+++ b/lib/Makefile
@@ -69,7 +69,7 @@ else
 	SHARED_EXT_VER = $(SHARED_EXT).$(LIBVER)
 endif

-LIBLZ4 = liblz4.$(SHARED_EXT_VER)
+LIBLZ4 = liblz4.$(SHARED_EXT)

 .PHONY: default
 default: lib-release
@@ -99,8 +99,6 @@ ifneq (,$(filter Windows%,$(OS)))
 else
 	@$(CC) $(FLAGS) -shared $^ -fPIC -fvisibility=hidden $(SONAME_FLAGS) -o $@
 	@echo creating versioned links
-	@ln -sf $@ liblz4.$(SHARED_EXT_MAJOR)
-	@ln -sf $@ liblz4.$(SHARED_EXT)
 endif
