{% set name = "kiwisolver" %}
{% set version = "1.3.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fc4453705b81d03568d5b808ad8f09c77c47534f6ac2e72e733f9ca4714aa75c" %}
package:
  name: android-{{ name|lower }}
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

requirements:
  build:
    - python
    - cppy
    - pip-cppy
    - android-ndk
    - android-libcxx
    - android-python * py{{PY_VER}}*
  run:
    - python
    - android-libcxx
    - android-python * py{{PY_VER}}*

build:
  binary_relocation: False
  noarch: generic

about:
  home: https://github.com/nucleic/atom
  summary: Memory efficient Python objects
  license: BSD
