package:
  name: android-ndk
  version: 25.2.9519653

requirements:
  build:
    - bison
    - flex

build:
  number: 1

test:
  commands:
    - source $PREFIX/android/activate-ndk.sh
    - activate-ndk-clang x86_64
    - $CC $RECIPE_DIR/test.c -llog

about:
  home: http://github.com/codelv/enaml-native
  summary: Android NDK with fortran support. Thanks to android-gfortran
  license: MIT

