{% set name = "cppy" %}
{% set version = "1.2.1" %}
package:
  name: pip-{{ name|lower }}
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83b43bf17b1085ac15c5debdb42154f138b928234b21447358981f69d0d6fe1b

build:
  number: 0
  noarch: true
  script:
  - export CC=/bin/false
  - export CXX=/bin/false
  - sed -i 's/setup()/setup(name=\"{{name}}\", version=\"{{version}}\")/g' setup.py
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/arm/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/arm64/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/x86/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/android/x86_64/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/iphoneos/python/site-packages '
  - 'python -m pip install . -vv --no-compile --target=$PREFIX/iphonesimulator/python/site-packages '

requirements: {}
about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: C++ headers for C extension development Built for Android and iOS apps using enaml-native.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
  - your-github-id-here
