{% set version = "1.22.2" %}
package:
  name: android-numpy
  version: '{{ version }}'

source:
  url: https://github.com/numpy/numpy/releases/download/v{{version}}/numpy-{{version}}.tar.gz
  sha256: 093d513a460fd94f94c16193c3ef29b2d69a33e482071e3d6d6e561a700587a6

requirements:
  build:
    - python
    - cython
    - android-ndk
    - android-python * py310*
  run:
    - python
    - android-python * py310*

build:
  number: 0
  binary_relocation: False
  noarch: generic
  string: 'py310'

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3
