context:
  version: 2.11.1

package:
  name: android-freetype
  version: '{{version}}'

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-{{version}}.tar.xz
  sha256: 3333ae7cfda88429c97a7ae63b7d01ab398076c3b67182e960e5684050f2c5c8

requirements:
  build:
    - android-libpng
    - android-harfbuzz
    - android-ndk
  run:
    - android-libpng
    - android-harfbuzz

build:
  number: 1
  binary_relocation: false
  noarch: generic

about:
  home: https://www.freetype.org/index.html
  summary: FreeType is a freely available software library to render fonts.
  license: FTL

