{% set version = "1.1.34" %}

package:
  name: android-libxslt
  version: '{{ version }}'

source:
  url: https://github.com/GNOME/libxslt/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 9a1af553b0bed564f0fb48c0902c4ef298cb21afc719f45ec52dbbcdd6fbe974

build:
  number: 1
  binary_relocation: False
  noarch: generic

requirements:
  build:
    - android-libxml2
    - android-ndk
  run:
    - android-libxml2
about:
  home: https://github.com/GNOME/libxslt
  summary:  an implementation of XSLT 1.0 and common extensions like EXSLT for libxml2. Built for Android apps using enaml-native.
  license:  MIT
