context:
  version: 3.4.2

package:
  name: android-libffi
  version: '{{version}}'

source:
  url: https://github.com/libffi/libffi/releases/download/v{{version}}/libffi-{{version}}.tar.gz
  sha256: 540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620

requirements:
  build:
    - android-ndk

build:
  number: 2
  binary_relocation: false
  noarch: generic

about:
  home: https://sourceware.org/libffi/
  summary: A portable foreign-function interface library.
  license: MIT

