package:
  name: ios-atom
  version: 0.4.2.a0

source:
  url: https://github.com/nucleic/atom/archive/0.4.2.a0.tar.gz
  #md5: e76cb77c242601810ff0ca363ce33b28

requirements:
  build:
    - ios-python
  run:
    - ios-python

build:
  number: 0
  binary_relocation: False

about:
  home: http://github.com/codelv/enaml-native
  license: GPLv3